### ISSUE TITLE
Running the storybook

### ISSUE THREAD

**Issue by soloviofff** [zignaly-open/zignaly-webapp#1198]
### My environment: 
	OSX 11.5.2 (m1 processor)
	node: v16.4.2
	npm: 7.18.1

I have an error when running the storybook:

```Error: Can't resolve '@storybook/addon-docs'```

**Comment by soloviofff** [comment]
The main problem is here - https://github.com/storybookjs/storybook/issues/15776
It can be solved temporarily by ```npm i @storybook/addon-docs --legacy-peer-deps```

**Comment by Xzirez** [comment]
Hi @soloviofff,  sorry for the late response here. The whole storybook is being refactored and was not a big priority when this issue was made. 

The new repository can be found here: https://github.com/zignaly-open/zignaly-ui

The npm package is currently being released at this endpoint: https://www.npmjs.com/package/zignaly-ui

If you have any more question be sure to let us know :)
